package com.programflow.programflow.enums;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.programflow.programflow.exception.ProgramFlowException;

import static com.programflow.programflow.enums.Region.*;
import static com.programflow.programflow.exception.ErrorType.INVALID_COUNTRY;


public enum Country {
    ANDORRA("Andorra", EUROPE),
    UNITED_ARAB_EMIRATES("United Arab Emirates", MIDDLE_EAST),
    AFGHANISTAN("Afghanistan", ASIA_PACIFIC),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", SOUTH_AMERICA),
    ANGUILLA("Anguilla", SOUTH_AMERICA),
    ALBANIA("Albania", EUROPE),
    ARMENIA("Armenia", EUROPE),
    NETHERLANDS_ANTILLES("Netherlands Antilles", SOUTH_AMERICA),
    ANGOLA("Angola", AFRICA),
    ANTARCTICA("Antarctica", ASIA_PACIFIC),
    ARGENTINA("Argentina", SOUTH_AMERICA),
    AMERICAN_SAMOA("American Samoa", ASIA_PACIFIC),
    AUSTRIA("Austria", EUROPE),
    AUSTRALIA("Australia", ASIA_PACIFIC),
    ARUBA("Aruba", SOUTH_AMERICA),
    AZERBAIJAN("Azerbaijan", ASIA_PACIFIC),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", EUROPE),
    BARBADOS("Barbados", SOUTH_AMERICA),
    BANGLADESH("Bangladesh", ASIA_PACIFIC),
    BELGIUM("Belgium", EUROPE),
    BURKINA_FASO("Burkina Faso", AFRICA),
    BULGARIA("Bulgaria", EUROPE),
    BAHRAIN("Bahrain", ARAB_STATES),
    BURUNDI("Burundi", AFRICA),
    BENIN("Benin", AFRICA),
    BERMUDA("Bermuda", NORTH_AMERICA),
    BRUNEI_DARUSSALAM("Brunei Darussalam", ASIA_PACIFIC),
    BOLIVIA("Bolivia", SOUTH_AMERICA),
    BRAZIL("Brazil", SOUTH_AMERICA),
    BAHAMAS("Bahamas", SOUTH_AMERICA),
    BHUTAN("Bhutan", ASIA_PACIFIC),
    BOUVET_ISLAND("Bouvet Island", SOUTH_AMERICA),
    BOTSWANA("Botswana", AFRICA),
    BELARUS("Belarus", EUROPE),
    BELIZE("Belize", SOUTH_AMERICA),
    CANADA("Canada", NORTH_AMERICA),
    COCOS_ISLANDS("Cocos (Keeling) Islands", ASIA_PACIFIC),
    CONGO_THE_DEMOCRATIC_REPUBLIC("Congo, The Democratic Republic of the", AFRICA),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", AFRICA),
    CONGO("Congo", AFRICA),
    SWITZERLAND("Switzerland", EUROPE),
    COTE_D_IVOIRE("Côte D'Ivoire", AFRICA),
    COOK_ISLANDS("Cook Islands", ASIA_PACIFIC),
    CHILE("Chile", SOUTH_AMERICA),
    CAMEROON("Cameroon", AFRICA),
    CHINA("China", ASIA_PACIFIC),
    COLOMBIA("Colombia", SOUTH_AMERICA),
    COSTA_RICA("Costa Rica", SOUTH_AMERICA),
    CUBA("Cuba", SOUTH_AMERICA),
    CAPE_VERDE("Cape Verde", AFRICA),
    CHRISTMAS_ISLAND("Christmas Island", ASIA_PACIFIC),
    CYPRUS("Cyprus", EUROPE),
    CZECH_REPUBLIC("Czech Republic", EUROPE),
    GERMANY("Germany", EUROPE),
    DJIBOUTI("Djibouti", ARAB_STATES),
    DENMARK("Denmark", EUROPE),
    DOMINICA("Dominica", SOUTH_AMERICA),
    DOMINICAN_REPUBLIC("Dominican Republic", SOUTH_AMERICA),
    ALGERIA("Algeria", ARAB_STATES),
    ECUADOR("Ecuador", SOUTH_AMERICA),
    ESTONIA("Estonia", EUROPE),
    EGYPT("Egypt", MIDDLE_EAST),
    WESTERN_SAHARA("Western Sahara", AFRICA),
    ERITREA("Eritrea", AFRICA),
    SPAIN("Spain", EUROPE),
    ETHIOPIA("Ethiopia", AFRICA),
    FINLAND("Finland", EUROPE),
    FIJI("Fiji", ASIA_PACIFIC),
    FALKLAND_ISLANDS("Falkland Islands (Malvinas)", SOUTH_AMERICA),
    MICRONESIA_FEDERATED_STATES_OF("Micronesia, Federated States of", ASIA_PACIFIC),
    FAROE_ISLANDS("Faroe Islands", EUROPE),
    FRANCE("France", EUROPE),
    FRANCE_METROPOLITAN("France, Metropolitan", EUROPE),
    GABON("Gabon", AFRICA),
    UNITED_KINGDOM("United Kingdom", EUROPE),
    GRENADA("Grenada", SOUTH_AMERICA),
    GEORGIA("Georgia", EUROPE),
    FRENCH_GUIANA("French Guiana", SOUTH_AMERICA),
    GHANA("Ghana", AFRICA),
    GIBRALTAR("Gibraltar", EUROPE),
    GREENLAND("Greenland", EUROPE),
    GAMBIA("Gambia", AFRICA),
    GUINEA("Guinea", AFRICA),
    GUADELOUPE("Guadeloupe", SOUTH_AMERICA),
    EQUATORIAL_GUINEA("Equatorial Guinea", AFRICA),
    GREECE("Greece", EUROPE),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("South Georgia and the South Sandwich Islands", SOUTH_AMERICA),
    GUATEMALA("Guatemala", SOUTH_AMERICA),
    GUAM("Guam", ASIA_PACIFIC),
    GUINEA_BISSAU("Guinea-Bissau", AFRICA),
    GUYANA("Guyana", SOUTH_AMERICA),
    HONG_KONG("Hong Kong", ASIA_PACIFIC),
    HEARD_AND_MCDONALD_ISLANDS("Heard Island and McDonald Islands", ASIA_PACIFIC),
    HONDURAS("Honduras", SOUTH_AMERICA),
    CROATIA("Croatia", EUROPE),
    HAITI("Haiti", SOUTH_AMERICA),
    HUNGARY("Hungary", EUROPE),
    INDONESIA("Indonesia", ASIA_PACIFIC),
    IRELAND("Ireland", EUROPE),
    ISRAEL("Israel", EUROPE),
    INDIA("India", ASIA_PACIFIC),
    BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory", ASIA_PACIFIC),
    IRAQ("Iraq", MIDDLE_EAST),
    IRAN("Iran, Islamic Republic of", MIDDLE_EAST),
    ICELAND("Iceland", EUROPE),
    ITALY("Italy", EUROPE),
    JAMAICA("Jamaica", SOUTH_AMERICA),
    JORDAN("Jordan", MIDDLE_EAST),
    JAPAN("Japan", ASIA_PACIFIC),
    KENYA("Kenya", AFRICA),
    KYRGYZSTAN("Kyrgyzstan", ASIA_PACIFIC),
    CAMBODIA("Cambodia", ASIA_PACIFIC),
    KIRIBATI("Kiribati", ASIA_PACIFIC),
    COMOROS("Comoros", ARAB_STATES),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", SOUTH_AMERICA),
    KOREA_DPR("Korea, Democratic People's Republic of", ASIA_PACIFIC),
    KOREA_RO("Korea, Republic of", ASIA_PACIFIC),
    KUWAIT("Kuwait", MIDDLE_EAST),
    CAYMAN_ISLANDS("Cayman Islands", SOUTH_AMERICA),
    KAZAKHSTAN("Kazakhstan", ASIA_PACIFIC),
    LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC("Lao People's Democratic Republic", ASIA_PACIFIC),
    LEBANON("Lebanon", MIDDLE_EAST),
    SAINT_LUCIA("Saint Lucia", SOUTH_AMERICA),
    LIECHTENSTEIN("Liechtenstein", EUROPE),
    SRI_LANKA("Sri Lanka", ASIA_PACIFIC),
    LIBERIA("Liberia", AFRICA),
    LESOTHO("Lesotho", AFRICA),
    LITHUANIA("Lithuania", EUROPE),
    LUXEMBOURG("Luxembourg", EUROPE),
    LATVIA("Latvia", EUROPE),
    LIBYA("Libya", MIDDLE_EAST),
    MOROCCO("Morocco", ARAB_STATES),
    MONACO("Monaco", EUROPE),
    MOLDOVA("Moldova, Republic of", EUROPE),
    MADAGASCAR("Madagascar", AFRICA),
    MARSHALL_ISLANDS("Marshall Islands", ASIA_PACIFIC),
    MACEDONIA("Macedonia", EUROPE),
    MALI("Mali", AFRICA),
    MYANMAR("Myanmar", ASIA_PACIFIC),
    MONGOLIA("Mongolia", ASIA_PACIFIC),
    MACAU("Macau", ASIA_PACIFIC),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands", ASIA_PACIFIC),
    MARTINIQUE("Martinique", SOUTH_AMERICA),
    MAURITANIA("Mauritania", ARAB_STATES),
    MONTSERRAT("Montserrat", SOUTH_AMERICA),
    MALTA("Malta", EUROPE),
    MAURITIUS("Mauritius", AFRICA),
    MALDIVES("Maldives", ASIA_PACIFIC),
    MALAWI("Malawi", AFRICA),
    MEXICO("Mexico", SOUTH_AMERICA),
    MALAYSIA("Malaysia", ASIA_PACIFIC),
    MOZAMBIQUE("Mozambique", AFRICA),
    NAMIBIA("Namibia", AFRICA),
    NEW_CALEDONIA("New Caledonia", ASIA_PACIFIC),
    NIGER("Niger", AFRICA),
    NORFOLK_ISLAND("Norfolk Island", ASIA_PACIFIC),
    NIGERIA("Nigeria", AFRICA),
    NICARAGUA("Nicaragua", SOUTH_AMERICA),
    NETHERLANDS("Netherlands", EUROPE),
    NORWAY("Norway", EUROPE),
    NEPAL("Nepal", ASIA_PACIFIC),
    NAURU("Nauru", ASIA_PACIFIC),
    NIUE("Niue", ASIA_PACIFIC),
    NEW_ZEALAND("New Zealand", ASIA_PACIFIC),
    OMAN("Oman", MIDDLE_EAST),
    PANAMA("Panama", SOUTH_AMERICA),
    PERU("Peru", SOUTH_AMERICA),
    FRENCH_POLYNESIA("French Polynesia", ASIA_PACIFIC),
    PAPUA_NEW_GUINEA("Papua New Guinea", ASIA_PACIFIC),
    PHILIPPINES("Philippines", ASIA_PACIFIC),
    PAKISTAN("Pakistan", ASIA_PACIFIC),
    POLAND("Poland", EUROPE),
    SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon", NORTH_AMERICA),
    PITCAIRN_ISLANDS("Pitcairn Islands", ASIA_PACIFIC),
    PUERTO_RICO("Puerto Rico", SOUTH_AMERICA),
    PALESTINIAN_TERRITORY("Palestinian Territory", ARAB_STATES),
    PORTUGAL("Portugal", EUROPE),
    PALAU("Palau", ASIA_PACIFIC),
    PARAGUAY("Paraguay", SOUTH_AMERICA),
    QATAR("Qatar", MIDDLE_EAST),
    REUNION("Reunion", ASIA_PACIFIC),
    ROMANIA("Romania", EUROPE),
    RUSSIAN("Russian Federation", EUROPE),
    RWANDA("Rwanda", AFRICA),
    SAUDI_ARABIA("Saudi Arabia", MIDDLE_EAST),
    SOLOMON_ISLANDS("Solomon Islands", ASIA_PACIFIC),
    SEYCHELLES("Seychelles", AFRICA),
    SOUTH_SUDAN("South Sudan", AFRICA),
    SUDAN("Sudan", ARAB_STATES),
    SWEDEN("Sweden", EUROPE),
    SINGAPORE("Singapore", ASIA_PACIFIC),
    SAINT_HELENA("Saint Helena", AFRICA),
    SLOVENIA("Slovenia", EUROPE),
    SVALBARD_AND_JAN_MAYEN("Svalbard and Jan Mayen", EUROPE),
    SLOVAKIA("Slovakia", EUROPE),
    SIERRA_LEONE("Sierra Leone", AFRICA),
    SAN_MARINO("San Marino", EUROPE),
    SENEGAL("Senegal", AFRICA),
    SOMALIA("Somalia", ARAB_STATES),
    SURINAME("Suriname", SOUTH_AMERICA),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", AFRICA),
    EL_SALVADOR("El Salvador", SOUTH_AMERICA),
    SYRIAN("Syrian Arab Republic", ASIA_PACIFIC),
    SWAZILAND("Swaziland", AFRICA),
    TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands", SOUTH_AMERICA),
    CHAD("Chad", AFRICA),
    FRENCH_SOUTHERN_TERRITORIES("French Southern Territories", ASIA_PACIFIC),
    TOGO("Togo", AFRICA),
    THAILAND("Thailand", ASIA_PACIFIC),
    TAJIKISTAN("Tajikistan", ASIA_PACIFIC),
    TOKELAU("Tokelau", ASIA_PACIFIC),
    TURKMENISTAN("Turkmenistan", ASIA_PACIFIC),
    TUNISIA("Tunisia", ARAB_STATES),
    TONGA("Tonga", ASIA_PACIFIC),
    TIMOR_LESTE("Timor-Leste", ASIA_PACIFIC),
    TURKEY("Turkey", EUROPE),
    TRINIDA_AND_TOBAGO("Trinidad and Tobago", SOUTH_AMERICA),
    TUVALU("Tuvalu", ASIA_PACIFIC),
    TAIWAN("Taiwan", ASIA_PACIFIC),
    TANZANIA("Tanzania, United Republic of", AFRICA),
    UKRAINE("Ukraine", EUROPE),
    UGANDA("Uganda", AFRICA),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("United States Minor Outlying Islands", ASIA_PACIFIC),
    UNITED_STATES("United States", NORTH_AMERICA),
    URUGUAY("Uruguay", SOUTH_AMERICA),
    UZBEKISTAN("Uzbekistan", ASIA_PACIFIC),
    HOLY_SEE("Holy See (Vatican City State)", EUROPE),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", SOUTH_AMERICA),
    VENEZUELA("Venezuela", SOUTH_AMERICA),
    VIRGIN_ISLANDS_BRITISH("Virgin Islands, British", SOUTH_AMERICA),
    VIRGIN_ISLANDS_U_S("Virgin Islands, U.S.", SOUTH_AMERICA),
    VIETNAM("Vietnam", ASIA_PACIFIC),
    VANUATU("Vanuatu", ASIA_PACIFIC),
    WALLIS_AND_FUTUNA("Wallis and Futuna", ASIA_PACIFIC),
    SAMOA("Samoa", ASIA_PACIFIC),
    YEMEN("Yemen", MIDDLE_EAST),
    MAYOTTE("Mayotte", AFRICA),
    SERBIA("Serbia", EUROPE),
    SOUTH_AFRICA("South Africa", AFRICA),
    ZAMBIA("Zambia", AFRICA),
    MONTENEGRO("Montenegro", EUROPE),
    ZIMBABWE("Zimbabwe", AFRICA),
    ALAND_ISLANDS("Aland Islands", EUROPE),
    GUERNSEY("Guernsey", EUROPE),
    ISLE_OF_MAN("Isle of Man", EUROPE),
    JERSEY("Jersey", EUROPE),
    SAINT_BARTHELEMY("Saint Barthelemy", SOUTH_AMERICA),
    SAINT_MARTIN("Saint Martin", SOUTH_AMERICA);


    private final String value;
    private final Region region;


    Country(String value, Region region) {
        this.value = value;
        this.region = region;
    }

    @JsonCreator
    public static Country getCountry(String value) {
        for (Country country : values())
            if (country.getValue().equalsIgnoreCase(value))
                return country;
        throw new ProgramFlowException(INVALID_COUNTRY);
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return getValue();
    }

    public Region getRegion() {
        return region;
    }
}
